### PR TITLE
(Able to be merged now) Changes to the assessment and add in images for the assessment and careers

### PR DESCRIPTION
**Pull request by tmloupe**
New spreadsheet that allows us to work with these changes:
https://docs.google.com/spreadsheets/d/1p6P_MlWz1EuNlE195nqF5_8p9AEmfgif6g1kp2n7cpY/pubhtml

Remember to go into the manage page and input the new SpreadSheet for it to accurately update

Some issues that I would like for people to help with:

- @bsabo We are missing a picture for the "Plumber" career in the Dropbox. Additionally, are you okay with mixing some of the old assessment pictures with new career pictures for the assessment test? 
- I'm in the process of changing some CSS after finding some issues and changing some pictures. Feel free to give suggestions
Looking for reviews on:
- How are the traits handled? Are they worded properly?
- Are the alt titles for each picture accurately describing the picture?

I am creating a pull request because it is functional; however, it is missing some aspects or there needs to be some change to pictures.

### CODE REVIEW

**Comment by bsabo** [comment]
Yes, currently used pix are fine.
Here is the plumber (best if cropped. If you can’t I can on my home computer that has graphic siftware.)

**Comment by tmloupe** [comment]
The code is ready to be merged, if anyone wants to. Please note that if this is merged you MUST use the spreadsheet indicated in the first comment of the pull request. It must be updated in the manage page, or the site will not understand the new traits and images!

**Comment by nihonjinrxs** [comment]
@tmloupe Note the red reports from CodeFactor and codacy. You should take a look at these and see if you can fix the issues there.

**Comment by tmloupe** [comment]
I apologize for the constant commits, I was trying to see what worked and what didn't work--every time I tried something new I got more errors. Eventually I got everything except codebeat actually degraded because the function definition is too long, but that _shouldn't_ be much of an issue, I think? All that's being found is whitespace from aligning the array elements at the bottom

**Pull request merged**
