### PR TITLE
Needed to update Ruby to 2.5.1

### PR DESCRIPTION
**Pull request by tmloupe**
AWS Elastic Beanstalk complained about ruby versioning. 2.2 is EOL and 2.2.5 is not supported within EB, so we made the change to 2.3.7. We also needed to update Sass to 3.6 because that was throwing a bunch of unfun warnings.

Needs to be tested before we push this into master to make sure the new Ruby update doesn't break. More to come.

### CODE REVIEW

**Comment by nihonjinrxs** [comment]
While we're updating, might be worthwhile to try and get to 2.5.3 (latest Ruby version). Not an imperative, but better to deliver on latest if possible.

**Comment by tmloupe** [comment]
Update: We went ahead and updated to 2.5.1 and ensured it worked - latest Ruby version is ready to go for a few more years!

**Comment by tmloupe** [comment]
I went through and did a test of the app and it seems like nothing has gone haywire. Looks safe to merge.

**Comment by nihonjinrxs** [comment]
OK, merging.

**Pull request merged**
